### ISSUE TITLE
Orientation assignment

### ISSUE THREAD

**Issue by ilyanelken** [scilus/ismrm_2015_tractography_challenge_scoring#4]
https://github.com/scilus/ismrm_2015_tractography_challenge_scoring/blob/db3c423850bd23a6e43160a49b38119fd24fbd54/scripts/score_tractogram.py#L154
@jchoude Hello, should there be an additional line:
> tract_attribute['orientation'] = args.orientation

Immediately after line 154

**Comment by jchoude** [comment]
Hi @ilyanelken 

sorry for the delay, this slipped through my emails. You are right, it was missing the assignment.

I added it in PR #5 , which is now merged.

Thanks for catching that!

**Comment by ilyanelken** [comment]
@jchoude Great, thanks!
